### ISSUE TITLE
Update note raise an error "NameError: global name 'cls' is not defined"

### ISSUE THREAD

**Issue by nledez** [feedmagnet/pyrise#50]
Hello, I try to update notes:
```python
from pyrise import Person
from pyrise import Highrise

Highrise.set_server('my-server')
Highrise.auth('my-token')

people = Person.filter(email='user@example.com')

for person in people:
    for note in person.notes:
        note.body = 'new text'
        print note.save()
```

But it raise an error:
```python
Traceback (most recent call last):
  File "/tmp/pyrise-save-note.py", line 12, in <module>
    print note.save()
  File "/usr/local/lib/python2.7/dist-packages/pyrise/__init__.py", line 469, in save
    new = cls.get(self.id)
NameError: global name 'cls' is not defined
```

**Comment by bykof** [comment]
Hey I have read your Ticket. Please be patient because I don't have much time to fix this issue. I will do it tommorow or on friday :)
Greetings Michael

**Comment by nledez** [comment]
Ok,

I have a temporary fix for the moment:
```python
try:
    note.save()
except NameError:
    pass
````

Thanks.
